/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Algorithm;

public class finerectangle {
    public Long solution(int w, int h) {
        long answer =0;
        long dividedSquare =0;
        for(int i =0; i< h; i++){
            dividedSquare = (w*i) /h ;
            answer += 2* dividedSquare;
        }
    return answer;
    }

    public static void main(String[] args) {
    finerectangle frect = new finerectangle();
    System.out.println(frect.solution(12, 8));
    
    }
}
