/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Algorithm;

public class NextBigNum {
    public void solution(int n) {
       
       
    }

    public static void main(String[] args) {
    System.out.println(Integer.toBinaryString(129));
    }
}
