/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Algorithm;

public class NextBigNum {
    public int solution(int n) {
       int answer =0;
       String a = Integer.toBinaryString(n);
      a.
       
       
       return answer;
    }

    public static void main(String[] args) {
    System.out.println(Integer.toBinaryString(129));
    }
}
